# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc-master/Nexys-A7-100T-Master.xdc

# Block Designs: bd/pll_design/pll_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pll_design || ORIG_REF_NAME==pll_design} -quiet] -quiet

# IP: bd/pll_design/ip/pll_design_clk_wiz_0_0/pll_design_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pll_design_clk_wiz_0_0 || ORIG_REF_NAME==pll_design_clk_wiz_0_0} -quiet] -quiet

# XDC: /home/dhep/vivado_proj/PLL/PLL.gen/sources_1/bd/pll_design/pll_design_ooc.xdc
